# This is a basic workflow that is manually triggered

name: echo
# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  add_device:
    runs-on: ubuntu-latest
    steps:
    - name: echo
      run: echo "work_flow_id ${{ github.ref_name }}"
